//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warframe
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Health { get; set; }
        public int Energy { get; set; }
        public int Armor { get; set; }
    }
}
